### ISSUE TITLE
qc band 6

### ISSUE THREAD

**Issue by JulKoch** [gee-hydro/gee_PML#3]
Is there any further documentation on how to interpret the bitmask for qc? In band 6, I find decimals, e.g. 4.25 or 2.25 and I am having troubles understanding these values. Is there a scaling I have overseen? 

Any help is highly appreciated. 

Best wishes
Julian

**Comment by kongdd** [comment]
If you export PML data in 500m scale, qc will be normal.
It is the problem of `pyramidingPolicy` (see details in `Export.image.toAsset`). But hard to solve.
